name: CI

on:
  schedule:
  - cron: 0 * * * *

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Yarn install
      run: yarn
    - name: Yarn run
      run: yarn test
